title: Dennis van Hulten
logo: assets/profile_image1.jpeg
description: PhD candidate at the University of Auckland.
about: "PhD candidate at the University of Auckland, New Zealand. Researching monostand forming coral species on tropical reefs."
follow_me: "This is where I would put my socials....       if i had any"
#show_downloads = True
theme: jekyll-theme-minimal

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "Publications"
    url: "/publications"
  - title: "Blog"
    url: "/blog"
  - title: "Outreach"
    url: "/outreach"
