title: Dennis van Hulten
logo: assets/profile_image1.jpeg
description: PhD candidate at the University of Auckland.
about: "PhD candidate at the University of Auckland, New Zealand. Researching coral species on tropical reefs."
follow_me: "Follow me on social media."
#show_downloads = True
theme: jekyll-theme-minimal

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "Blog"
    url: "/blog"
  - title: "Publications"
    url: "/publications"
